name: Synchronisation du Dépôt

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # Empêche l'utilisation du GITHUB_TOKEN par défaut

      - name: Configurer Git
        run: |
          git config --global user.email "noreply"
          git config --global user.name "Thomas-TP"

      - name: Push vers le dépôt de destination
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Utilisation d'une URL propre avec le token pour l'authentification
          # On s'assure de supprimer toute configuration de remote existante pour être propre
          git remote remote remove destination || true
          git remote add destination "https://Thomas-TP:${SYNC_TOKEN}@github.com/Satom-IT-Learning-Solutions/HelpDesk-GIT.git"
          
          # Tentative de push forcé sur master
          git push destination master --force
