name: Synchronisation du Dépôt

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  repo-sync:
    # On s'assure que l'action ne s'exécute QUE sur le dépôt source
    if: github.repository == 'Thomas-TP/HelpDesk-GIT'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configurer Git
        run: |
          git config --global user.email "noreply"
          git config --global user.name "Thomas-TP"

      - name: Push vers le dépôt de destination
        env:
          SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Nettoyage et ajout du remote de destination
          git remote remove destination || true
          git remote add destination "https://Thomas-TP:${SYNC_TOKEN}@github.com/Satom-IT-Learning-Solutions/HelpDesk-GIT.git"
          
          # Push forcé pour maintenir la synchro
          git push destination master --force
